В 2025-08-19 10:09:04 - функция test_2 c аргументами () и {} выполнилась и вернула Тест пройден успешно
